version: '3.8'

services:
  oracledb:
    image: gvenzl/oracle-xe:11
    container_name: oracledb
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - oracle-data:/u01/app/oracle/oradata
    networks:
      - oracle

  sqldeveloper:
    image: usersina/sqldeveloper
    container_name: sqldeveloper
    ports:
      - 5900:5900
    volumes:
      - sqldeveloper-data:/data
    networks:
      - oracle

volumes:
  oracle-data:
    driver: local
  sqldeveloper-data:
    driver: local

networks:
  oracle:
    name: oracle-network
    driver: bridge
